### PR TITLE
forked pr

### PR DESCRIPTION
**Pull request by Boss-1s**

### CODE REVIEW

**Comment by jgrajewsky** [comment]
.md files are Markdown files and the `COPYING` file is just plain text.
Also that `.gitignore` seems kinda random.

**Comment by boscokwong** [comment]
I actually choose a template for the `.gitignore`, it was the C template.
And for the license I can fix that.

**Comment by jgrajewsky** [comment]
The project isn't actually written in C.

**Comment by boscokwong** [comment]
oh.

**Comment by jgrajewsky** [comment]
And not JavaScript either.

**Pull request closed without merging**
